# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-05 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkuDetails',
            fields=[
                ('sku_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_name', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_skudetails', to='product.Category')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_skudetails', to='product.Department')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_skudetails', to='product.Location')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_cate_name', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cate_subcategory', to='product.Category')),
            ],
        ),
        migrations.AddField(
            model_name='skudetails',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory_skudetails', to='product.SubCategory'),
        ),
        migrations.AddField(
            model_name='department',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loc_department', to='product.Location'),
        ),
        migrations.AddField(
            model_name='category',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dept_category', to='product.Department'),
        ),
    ]
